---
swagger: "2.0"
info:
  version: "2024-06-15T21:36:49Z"
  title: "ProductServiceKate"
host: "cdyw64p935.execute-api.eu-central-1.amazonaws.com"
basePath: "/prod"
schemes:
  - "https"
paths:
  /products:
    get:
      responses: {}
  /products/{id}:
    get:
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
      responses: {}
